# Form implementation generated from reading ui file '/Users/andreykovalskiy/Desktop/AES encryptor/design/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setFixedSize(868, 227)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 871, 311))
        self.frame.setStyleSheet("background: #959595; color: black;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.encrypt_btn = QtWidgets.QPushButton(parent=self.frame)
        self.encrypt_btn.setGeometry(QtCore.QRect(10, 160, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.encrypt_btn.setFont(font)
        self.encrypt_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.encrypt_btn.setStyleSheet("QPushButton {\n"
"    background: #BABABA;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #CDCDCD;\n"
"}")
        self.encrypt_btn.setObjectName("encrypt_btn")
        self.decrypt_btn = QtWidgets.QPushButton(parent=self.frame)
        self.decrypt_btn.setGeometry(QtCore.QRect(440, 160, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.decrypt_btn.setFont(font)
        self.decrypt_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.decrypt_btn.setStyleSheet("QPushButton {\n"
"    background: #BABABA;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #CDCDCD;\n"
"}")
        self.decrypt_btn.setObjectName("decrypt_btn")
        self.file_path = QtWidgets.QLineEdit(parent=self.frame)
        self.file_path.setEnabled(False)
        self.file_path.setGeometry(QtCore.QRect(10, 10, 611, 41))
        self.file_path.setStyleSheet("QLineEdit {\n"
"    background: #FFFFFF;\n"
"    border-radius: 20px;\n"
"    padding-left: 5px;\n"
"}")
        self.file_path.setText("")
        self.file_path.setObjectName("file_path")
        self.chose_file_path_btn = QtWidgets.QPushButton(parent=self.frame)
        self.chose_file_path_btn.setGeometry(QtCore.QRect(630, 10, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.chose_file_path_btn.setFont(font)
        self.chose_file_path_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.chose_file_path_btn.setStyleSheet("QPushButton {\n"
"    background: #BABABA;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #CDCDCD;\n"
"}")
        self.chose_file_path_btn.setObjectName("chose_file_path_btn")
        self.password = QtWidgets.QLineEdit(parent=self.frame)
        self.password.setGeometry(QtCore.QRect(10, 60, 611, 41))
        self.password.setStyleSheet("QLineEdit {\n"
"    background: #FFFFFF;\n"
"    border-radius: 20px;\n"
"    padding-left: 5px;\n"
"}")
        self.password.setText("")
        self.password.setObjectName("password")
        self.generate_password_btn = QtWidgets.QPushButton(parent=self.frame)
        self.generate_password_btn.setGeometry(QtCore.QRect(630, 60, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.generate_password_btn.setFont(font)
        self.generate_password_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.generate_password_btn.setStyleSheet("QPushButton {\n"
"    background: #BABABA;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #CDCDCD;\n"
"}")
        self.generate_password_btn.setObjectName("generate_password_btn")
        self.creation_dir = QtWidgets.QLineEdit(parent=self.frame)
        self.creation_dir.setGeometry(QtCore.QRect(10, 110, 611, 41))
        self.creation_dir.setStyleSheet("QLineEdit {\n"
"    background: #FFFFFF;\n"
"    border-radius: 20px;\n"
"    padding-left: 5px;\n"
"}")
        self.creation_dir.setText("")
        self.creation_dir.setEnabled(False)
        self.creation_dir.setObjectName("creation_dir")
        self.chose_creation_path_btn = QtWidgets.QPushButton(parent=self.frame)
        self.chose_creation_path_btn.setGeometry(QtCore.QRect(630, 110, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.chose_creation_path_btn.setFont(font)
        self.chose_creation_path_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.chose_creation_path_btn.setStyleSheet("QPushButton {\n"
"    background: #BABABA;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #CDCDCD;\n"
"}")
        self.chose_creation_path_btn.setObjectName("chose_creation_path_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AES encryptor"))
        self.encrypt_btn.setText(_translate("MainWindow", "Шифрувати"))
        self.decrypt_btn.setText(_translate("MainWindow", "Розшифрувати"))
        self.file_path.setPlaceholderText(_translate("MainWindow", "Шлях до файлу (для шифрування, розшифрування)"))
        self.chose_file_path_btn.setText(_translate("MainWindow", "Вибрати..."))
        self.password.setPlaceholderText(_translate("MainWindow", "Пароль (для шифрування та розшифрування)"))
        self.generate_password_btn.setText(_translate("MainWindow", "Згенерувати пароль..."))
        self.creation_dir.setPlaceholderText(_translate("MainWindow", "Папка, куди шифрувати та розшифровувати файл (за замовчюванням у директорію файлу)"))
        self.chose_creation_path_btn.setText(_translate("MainWindow", "Вибрати..."))
